### PR TITLE
Tdelmiro patch 2

### PR DESCRIPTION
**Pull request by tdelmiro**
check this out

### CODE REVIEW

**Review by thalesdelmiro — CHANGES_REQUESTED** [review]
Could you add a space at the end of the text?

**Comment by tdelmiro** [comment]
Where?

**Comment by thalesdelmiro** [comment]
In the README.md file, please!

**Comment by tdelmiro** [comment]
Ok! I got it.

**Comment by thalesdelmiro** [comment]
Nice! Im doing a rebase and merge.

**Pull request merged**
